groups:
  - name: rate-alerting
    rules:
      - alert: HighLogRate
        expr: |
          sum by(job) (rate({job=~"neutron-node-1"} |= `` | json | level = `debug` | module = `p2p` [1m]))
            > 4
        for: 1m
        labels:
          severity: critical
        #     team: devops
        #     category: logs
        annotations:
          title: "High LogRate Alert"
          description: "something is logging a lot"
          priority: P1
          service: neutron