{
 "title": "Neutron nodes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Base stuff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Minted tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "minted_tokens" }
   ]
  },
  {
   "title": "Cpu time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "delta(process_cpu_seconds_total{job=\"neutron\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Neutron number of goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "runtime_num_goroutines" }
   ]
  },
  {
   "title": "Neutron process resident memory Mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"neutron\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Neutron Process virtual memory Mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"neutron\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Neutron Number of heap objects M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "runtime_heap_objects{job=\"neutron\"} / 1000000"
    }
   ]
  },
  {
   "title": "Node Number of heap objects M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "runtime_heap_objects{job=\"node\"} / 1000000"
    }
   ]
  },
  {
   "title": "Node Begin Blockers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capability",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"capability\", job=\"node\"}"
      }
     ]
    },
    {
     "title": "Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"distribution\", job=\"node\"}"
      }
     ]
    },
    {
     "title": "Evidence",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"evidence\", job=\"node\"}"
      }
     ]
    },
    {
     "title": "Mint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"mint\", job=\"node\"}"
      }
     ]
    },
    {
     "title": "Slashing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"slashing\", job=\"node\"}"
      }
     ]
    },
    {
     "title": "Staking",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"staking\", job=\"node\"}"
      }
     ]
    },
    {
     "title": "Upgrade",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"upgrade\", job=\"node\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node End Blockers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Crisis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "end_blocker{module=\"crisis\", job=\"node\"}"
      }
     ]
    },
    {
     "title": "Gov",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "end_blocker{module=\"gov\", job=\"node\"}"
      }
     ]
    },
    {
     "title": "Staking",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 11 },
     "targets": [
      {
       "expr": "end_blocker{module=\"staking\", job=\"node\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Neutron Begin blocker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capability",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"capability\", job=\"neutron\"}"
      }
     ]
    },
    {
     "title": "Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"distribution\", job=\"neutron\"}"
      }
     ]
    },
    {
     "title": "Evidence",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"evidence\", job=\"neutron\"}"
      }
     ]
    },
    {
     "title": "Mint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"mint\", job=\"neutron\"}"
      }
     ]
    },
    {
     "title": "Slashing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"slashing\", job=\"neutron\"}"
      }
     ]
    },
    {
     "title": "Staking",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"staking\", job=\"neutron\"}"
      }
     ]
    },
    {
     "title": "Upgrade",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "begin_blocker{module=\"upgrade\", job=\"neutron\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Neutron End blocker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Crisis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "end_blocker{module=\"crisis\", job=\"neutron\"}"
      }
     ]
    },
    {
     "title": "Gov",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "end_blocker{module=\"gov\", job=\"neutron\"}"
      }
     ]
    },
    {
     "title": "Staking",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 13 },
     "targets": [
      {
       "expr": "end_blocker{module=\"staking\", job=\"neutron\"}"
      }
     ]
    }
   ]
  }
 ]
}