groups:
- name: example
  rules:
  - alert: NeutronResidentMemory
    expr: process_resident_memory_bytes{job="neutron"} / 1024 / 1024 > 1100
    for: 5m
    annotations:
      service: neutron
      summary: "Neutron instance {{ $labels.instance }} high on resident memory"
      description: "{{ $labels.instance }} resident memory: {{ $value }} Mbytes"
